version: '3.9'

x-base_service: &base_service
  ports:
    - "${WEBUI_PORT:-7860}:7860"
  volumes:
    - &v1 ./stable-diffusion-webui-docker/data:/data
    - &v2 ./stable-diffusion-webui-docker/output:/output
  stop_signal: SIGKILL
  tty: true
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [compute, utility]

services:
  auto: &automatic
    <<: *base_service
    profiles: [ "auto" ]
    build: ./stable-diffusion-webui-docker/service
    image: sd-auto:68
    hostname: auto
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api

  auto-cpu:
    <<: *automatic
    profiles: [ "auto-cpu" ]
    deploy: { }
    hostname: auto
    environment:
      - CLI_ARGS=--no-half --precision full --allow-code --enable-insecure-extension-access --api

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '3306:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  rabbitmq:
    image: 'rabbitmq:latest'
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - '5672:5672'
      - '15672:15672'
