server:
  port: 8080
api:
  url: auto-cpu:7860
spring:
  jackson:
    date-format: team.polytech.online.diffusion.RFC3339DateFormat
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis
      port: 6379
  rabbitmq:
    username: rmuser
    password: rmpassword
    host: rabbitmq
    port: 5672