spring.profiles.include: secrets, photomock
server:
  port: 8080
spring:
  paging:
    page-size: 2
  jackson:
    date-format: team.polytech.online.diffusion.RFC3339DateFormat
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:postgresql://localhost:3306/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    username: rmuser
    password: rmpassword
    host: localhost
    port: 5672
stable-diffusion:
  mock:
    enabled: true
    time-ms: 5000