spring.profiles.include: secrets, photomock
server:
  port: 8080
api:
  url: localhost:7860
spring:
  paging:
    post-amount: 20
    image-amount: 32
  jackson:
    date-format: team.polytech.online.diffusion.RFC3339DateFormat
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:postgresql://localhost:3306/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    username: rmuser
    password: rmpassword
    host: localhost
    port: 5672
  docker:
    compose:
      enabled: true
      file: docker-compose-local.yml
  mail:
    host: smtp-relay.brevo.com
    port: 587
    properties:
      smtp:
        auth: true
        starttls:
          enable=true:
stable-diffusion:
  url: http://127.0.0.1:7860
  mock:
    enabled: true
    time-ms: 5000
  conf:
    easy-negative-enabled: true